apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.movieDB.name }}
spec:
  replicas: {{ .Values.movieDB.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.movieDB.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.movieDB.label }}
    spec:
      containers:
      - name: {{ .Values.movieDB.containerName }}
        image: "{{ .Values.movieDB.image }}"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.movieDB.env.POSTGRES_DB }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movieDB.env.POSTGRES_PASSWORD }}
        - name: POSTGRES_USER
          value: {{ .Values.movieDB.env.POSTGRES_USER }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Values.movieDB.pvc.name }}
