apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castService.service.name }}
spec:
  type: {{ .Values.castService.service.type }}
  ports:
  - name: "{{ .Values.castService.service.portName }}"
    port: {{ .Values.castService.service.port }}
    targetPort: {{ .Values.castService.port }}
  selector:
    app: {{ .Values.castService.label }}
